import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#000' },
    centeredView: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    // ZMIANA: Modyfikujemy padding, aby zrobić miejsce
    scrollContent: { padding: 16, paddingTop: 60 },
    // ZMIANA: Modyfikujemy nagłówek
    header: {
        fontFamily: 'JosefinSans_700Bold',
        fontSize: 32,
        color: '#EAEAEA',
        textAlign: 'center',
        marginBottom: 20,
        paddingTop: 20 // Dodajemy padding, aby odsunąć od góry
    },
    widget: { borderRadius: 28, padding: 20, marginBottom: 16 },
    darkWidget: { backgroundColor: '#1C1C1E' },
    pinkWidget: { backgroundColor: '#F4C2C4' },
    widgetTitle: { fontFamily: 'JosefinSans_700Bold', fontSize: 18, marginBottom: 16, color: 'black' },
    widgetTitleSmall: { fontFamily: 'JosefinSans_700Bold', fontSize: 12, letterSpacing: 1 },
    timeInputContainerWidget: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginVertical: 16 },
    timeInputWidget: { backgroundColor: 'rgba(0,0,0,0.1)', color: 'black', fontFamily: 'JosefinSans_700Bold', fontSize: 52, textAlign: 'center', width: 120, borderRadius: 12, paddingVertical: 8 },
    timeSeparatorWidget: { fontFamily: 'JosefinSans_700Bold', fontSize: 40, color: 'black', marginHorizontal: 8 },
    buttonBlack: { backgroundColor: 'black', paddingVertical: 16, borderRadius: 12, alignItems: 'center', marginTop: 16 },
    buttonBlackText: { color: 'white', fontFamily: 'JosefinSans_600SemiBold', fontSize: 16 },
    // ZMIANA: Modyfikujemy pozycję zegara
    topRightClock: { position: 'absolute', top: 50, right: 24, zIndex: 10, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 20 },
    topRightClockIcon: { fontSize: 20, marginRight: 8, color: 'white' },
    topRightClockText: { color: 'white', fontFamily: 'JosefinSans_600SemiBold', fontSize: 16 },
    dateWidgetDay: { color: 'white', fontFamily: 'JosefinSans_700Bold', fontSize: 24, letterSpacing: 1 },
    dateWidgetDate: { color: '#9CA3AF', fontFamily: 'JosefinSans_600SemiBold', fontSize: 18 },
    timeline: { paddingLeft: 16, borderLeftWidth: 2 },
    timelineItem: { paddingLeft: 24, marginBottom: 16 },
    timelineDot: { position: 'absolute', left: -9, top: 5, width: 16, height: 16, borderRadius: 8 },
    timelineTitle: { fontFamily: 'JosefinSans_600SemiBold', fontSize: 15, color: 'white' },
    timelineTime: { fontFamily: 'JosefinSans_400Regular', fontSize: 13, color: '#9CA3AF' },
    emptyTimelineText: { fontFamily: 'JosefinSans_400Regular', fontSize: 14, textAlign: 'center', padding: 16, opacity: 0.8 },
    freeTimeSlot: { paddingLeft: 24, marginBottom: 16 },
    addEventText: { fontFamily: 'JosefinSans_600SemiBold', fontSize: 13, color: 'rgba(255,255,255,0.5)'},
    addButton: { height: 32, width: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
    calendarHeader: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 8 },
    calendarDayName: { color: '#9CA3AF', fontFamily: 'JosefinSans_700Bold', fontSize: 12, letterSpacing: 1 },
    calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
    calendarCell: { width: `${100/7}%`, aspectRatio: 1, justifyContent: 'center', alignItems: 'center' },
    calendarDay: { width: 32, height: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
    calendarDayToday: { backgroundColor: 'white' },
    calendarDaySelected: { backgroundColor: 'rgba(255, 255, 255, 0.7)' },
    dotsContainer: { flexDirection: 'row', gap: 2, marginTop: 2 },
    eventDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#F2A413' },
    majordomoModalView: { margin: 20, backgroundColor: "#1C1C1E", borderRadius: 28, padding: 24, alignItems: "center", width: '90%' },
    majordomoTitle: { fontFamily: 'JosefinSans_700Bold', fontSize: 22, color: 'white', textAlign: 'center' },
    majordomoSubtitle: { fontFamily: 'JosefinSans_400Regular', color: '#9CA3AF', textAlign: 'center', marginTop: 8, marginBottom: 24 },
    suggestionCard: { flexDirection: 'row', alignItems: 'center', gap: 16, backgroundColor: 'rgba(255,255,255,0.05)', padding: 16, borderRadius: 16, width: '100%', marginBottom: 12 },
    suggestionTitle: { color: 'white', fontFamily: 'JosefinSans_600SemiBold' },
    suggestionDesc: { color: '#9CA3AF', fontFamily: 'JosefinSans_400Regular', fontSize: 12 },
    suggestionButton: { width: 32, height: 32, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
    closeMajordomoButton: { backgroundColor: '#374151', paddingVertical: 16, borderRadius: 12, alignItems: 'center', marginTop: 16, width: '100%' },
    editModalContainer: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.6)' },
    editModalContent: { backgroundColor: '#1C1C1E', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24 },
    modalTitle: { fontFamily: 'JosefinSans_700Bold', fontSize: 22, color: 'white', marginBottom: 24 },
    inputLabel: { fontFamily: 'JosefinSans_700Bold', fontSize: 12, letterSpacing: 1, color: '#9CA3AF', marginBottom: 8, marginTop: 16 },
    modalInput: { backgroundColor: '#374151', color: 'white', borderRadius: 12, padding: 16, fontSize: 16, fontFamily: 'JosefinSans_400Regular' },
    timeInputContainerModal: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
    timeInputModal: { backgroundColor: '#374151', color: 'white', fontFamily: 'JosefinSans_600SemiBold', fontSize: 18, textAlign: 'center', flex: 1, borderRadius: 12, paddingVertical: 16 },
    timeSeparatorModal: { fontFamily: 'JosefinSans_600SemiBold', fontSize: 24, color: '#9CA3AF', marginHorizontal: 10 },
    modalButtonRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 32 },
    cancelButton: { backgroundColor: '#4b5563', flex: 1, marginRight: 8, paddingVertical: 16, borderRadius: 12, alignItems: 'center' },
    cancelButtonText: { color: '#EAEAEA', fontFamily: 'JosefinSans_600SemiBold', fontSize: 16 },
    saveButton: { backgroundColor: 'white', flex: 1, marginLeft: 8, paddingVertical: 16, borderRadius: 12, alignItems: 'center' },
});