import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#121212' },
  scrollContent: { padding: 20, paddingTop: 60 },
  header: { fontSize: 32, fontWeight: 'bold', color: '#EAEAEA', textAlign: 'center', marginBottom: 20 },
  card: { backgroundColor: '#1E1E1E', borderRadius: 15, padding: 20, marginBottom: 25, borderWidth: 1, borderColor: '#2a2a2a' },
  cardTitle: { fontSize: 22, fontWeight: '600', color: '#EAEAEA', marginBottom: 15 },
  button: { backgroundColor: '#3498db', paddingVertical: 15, borderRadius: 10, alignItems: 'center' },
  buttonText: { color: '#FFFFFF', fontSize: 18, fontWeight: 'bold' },
  timeInputContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginVertical: 20 },
  timeInput: { color: '#EAEAEA', backgroundColor: '#2c2c2c', fontSize: 48, fontWeight: 'bold', textAlign: 'center', width: 100, borderRadius: 10, paddingVertical: 10 },
  timeSeparator: { color: '#EAEAEA', fontSize: 48, marginHorizontal: 10 },
  topRightClock: { position: 'absolute', top: 15, right: 20, zIndex: 10, flexDirection: 'row', alignItems: 'center', backgroundColor: '#2c2c2c', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 20 },
  topRightClockIcon: { fontSize: 20, marginRight: 8 },
  topRightClockText: { color: '#EAEAEA', fontWeight: '600', fontSize: 16 },
  moodSelectorCompact: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginBottom: 25, paddingVertical: 10 },
  moodLabel: { color: '#9ca3af', marginRight: 16, fontSize: 16 },
  moodButtonsContainer: { flexDirection: 'row', gap: 10 },
  moodButton: { padding: 10, borderRadius: 50, borderWidth: 1, borderColor: '#555' },
  moodButtonSelected: { backgroundColor: '#3498db', borderColor: '#3498db' },
  moodButtonText: { fontSize: 20 },
  moodButtonTextSelected: { fontSize: 20 },
  planIntro: { color: '#d1d5db', marginBottom: 20, fontSize: 16, fontStyle: 'italic' },
  dayHeader: { fontSize: 18, fontWeight: 'bold', color: '#EAEAEA', marginTop: 15, marginBottom: 10 },
  timeline: { paddingLeft: 15, borderLeftWidth: 2, borderColor: '#374151' },
  timelineItem: { position: 'relative', paddingLeft: 25, paddingBottom: 0, marginBottom: 10 },
  timelineDot: { position: 'absolute', left: -9, top: 5, width: 16, height: 16, borderRadius: 8, borderWidth: 3, borderColor: '#1E1E1E' },
  timelineContent: { borderRadius: 8, paddingVertical: 12, paddingHorizontal: 16 },
  timelineTime: { color: 'rgba(255, 255, 255, 0.8)', fontWeight: '500', marginBottom: 4 },
  timelineTitle: { color: 'white', fontWeight: '600', fontSize: 16 },
  freeTimeSlot: { flexDirection: 'row', alignItems: 'center', marginVertical: 15, paddingLeft: 5 },
  freeTimePlus: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: '#4b5563', borderStyle: 'dashed', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  freeTimePlusText: { color: '#4b5563', fontWeight: '600', fontSize: 16 },
  freeTimeText: { color: '#6b7280', fontSize: 14 },
  editModalContainer: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.6)' },
  editModalContent: { backgroundColor: '#1E1E1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 30, shadowColor: '#000', shadowOffset: { width: 0, height: -3 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 5 },
  modalTitle: { fontSize: 18, fontWeight: '600', color: '#EAEAEA', marginBottom: 20 },
  inputLabel: { color: '#9ca3af', fontSize: 14, marginBottom: 8, marginTop: 15 },
  modalInput: { backgroundColor: '#2c2c2c', color: '#EAEAEA', borderRadius: 8, padding: 12, fontSize: 16 },
  timeInputContainerModal: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  timeInputModal: { color: '#EAEAEA', backgroundColor: '#2c2c2c', fontSize: 24, fontWeight: 'bold', textAlign: 'center', flex: 1, borderRadius: 8, paddingVertical: 10 },
  timeSeparatorModal: { color: '#EAEAEA', fontSize: 24, marginHorizontal: 10 },
  modalButtonRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 30 },
  cancelButton: { backgroundColor: '#4b5563', flex: 1, marginRight: 10 },
  cancelButtonText: { color: '#EAEAEA' },
  saveButton: { flex: 1, marginLeft: 10 },
  colorSelector: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10 },
  colorCircle: { width: 40, height: 40, borderRadius: 20, borderWidth: 2, borderColor: 'transparent' },
  colorCircleSelected: { borderColor: 'white', transform: [{ scale: 1.1 }] }
});